baseURL = 'https://animebgm.com/'
languageCode = 'ja-jp'
title = 'アニメ系 BGM'
theme = 'chord'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  
  [[menus.main]]
    name = 'About'
    pageRef = '/page/about/'
    weight = 20

[module]
  [module.hugoVersion]
    extended = true
    min = '0.146.0'

[params.license]
  link = '/terms-of-service/'
  text = '利用規約はこちら'

  [[params.license.main]]
    svg = 'svg/businessplan.svg'
    text = '商用OK'
    weight = 10

  [[params.license.main]]
    svg = 'svg/free-rights.svg'
    text = '完全無料'
    weight = 20

  [[params.license.main]]
    svg = 'svg/report-off.svg'
    text = '報告不要'
    weight = 30

  [[params.license.main]]
    svg = 'svg/ban.svg'
    text = 'AIなし'
    weight = 40

[params]
  copyright = 'icysamon'
  homepageurl = 'https://animebgm.com'

[permalinks]
  post = '/post/:year/:month/:slug/'
  page = '/:slug/'

[Params]
  [Assets]
    favicon = '/favicon.ico'