baseURL = 'https://animebgm.com/'
languageCode = 'en-US'
title = 'Anime BGM'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = true
    min = '0.146.0'

[params]
  copyright = 'icysamon'
  homepageurl = 'https://icysamon.com'
